services:
  build-extension:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - VITE_API=https://api.widgetify.ir
    volumes:
      - ./local_output:/app/.output
    command: >
      sh -c "npm run clean &&
             npm run build:firefox &&
             npm run zip:firefox:clean"
