import {
	FiBell,
	FiClock,
	FiInbox,
	FiKey,
	FiLoader,
	FiLock,
	FiMail,
	FiMaximize,
	FiMinimize,
	FiRotateCcw,
	FiSettings,
	FiShoppingBag,
	FiShoppingCart,
	FiTrash2,
	FiUser,
	FiUserCheck,
	FiUsers,
	FiUserX,
} from 'react-icons/fi'
import type { IconMap } from '../types'
import { TfiAlert, TfiBackRight, TfiCheck } from 'react-icons/tfi'
import {
	LuBriefcase,
	LuCalendarDays,
	LuChevronDown,
	LuChevronLeft,
	LuChevronRight,
	LuChevronUp,
	LuDownload,
	LuHistory,
	LuPen,
	LuPlus,
	LuX,
} from 'react-icons/lu'
import { TiInfo } from 'react-icons/ti'
import {
	FaBrush,
	FaCoins,
	FaExternalLinkAlt,
	FaGithub,
	FaGlobe,
	FaImage,
	FaPaintBrush,
	FaSpinner,
	FaTelegramPlane,
	FaUpload,
} from 'react-icons/fa'
import {
	TbCloudOff,
	TbUsersPlus,
	TbBookmarkPlus,
	TbCameraPlus,
	TbWind,
} from 'react-icons/tb'
import {
	MdFolderSpecial,
	MdLink,
	MdMic,
	MdOutlinePrivacyTip,
	MdOutlineVerifiedUser,
	MdSearch,
} from 'react-icons/md'
import {
	HiHome,
	HiInbox,
	HiOutlineBookmark,
	HiOutlineEye,
	HiOutlineEyeSlash,
	HiOutlineFolder,
	HiOutlineGlobeAlt,
	HiOutlineHome,
	HiOutlineInbox,
	HiOutlineInformationCircle,
	HiOutlineShoppingBag,
	HiOutlineSquares2X2,
	HiOutlineUserGroup,
	HiSquares2X2,
} from 'react-icons/hi2'
import { FaFolder, FaFolderOpen } from 'react-icons/fa'
import { GoArchive, GoKebabHorizontal } from 'react-icons/go'
import { IoMdHelp } from 'react-icons/io'
import { FaPhotoFilm } from 'react-icons/fa6'
import { BiCalendar, BiLogoGoogle } from 'react-icons/bi'
import { FcGoogle } from 'react-icons/fc'
import { CiLocationOn } from 'react-icons/ci'
import { WiCloudy, WiHumidity } from 'react-icons/wi'
import { RiQuillPenAiLine } from 'react-icons/ri'
import { AiOutlineDrag } from 'react-icons/ai'
import { HiOutlineViewGridAdd } from 'react-icons/hi'

export const defaultIcons = {
	home: HiHome,
	calendar: BiCalendar,
	settings: FiSettings,
	search: MdSearch,
	user: FiUser,
	clock: FiClock,
	notification: FiBell,
	alert: TfiAlert,
	check: TfiCheck,
	close: LuX,
	info: HiOutlineInformationCircle,
	externalLink: FaExternalLinkAlt,
	offline: TbCloudOff,
	chevronUp: LuChevronUp,
	chevronDown: LuChevronDown,
	chevronLeft: LuChevronLeft,
	chevronRight: LuChevronRight,
	lock: FiLock,
	verifyUser: MdOutlineVerifiedUser,
	outlineEye: HiOutlineEye,
	outlineEyeSlash: HiOutlineEyeSlash,
	trash: FiTrash2,
	spinner: FaSpinner,
	backRight: TfiBackRight,
	loader: FiLoader,
	usersPlus: TbUsersPlus,
	bookmarkPlus: TbBookmarkPlus,
	folder: FaFolder,
	folderOpen: FaFolderOpen,
	menuOption: GoKebabHorizontal,
	uploadImage: FaUpload,
	image: FaImage,
	help: IoMdHelp,
	outlineBookmark: HiOutlineBookmark,
	outlineFolder: HiOutlineFolder,
	reload: FiRotateCcw,
	plus: LuPlus,
	pen: LuPen,
	users: FiUsers,
	userCheck: FiUserCheck,
	userX: FiUserX,
	outlineInbox: HiOutlineInbox,
	inbox: FiInbox,
	brush: FaPaintBrush,
	photoFilm: FaPhotoFilm,
	coin: FaCoins,
	shoppingCart: FiShoppingCart,
	shoppingBag: FiShoppingBag,
	maximize: FiMaximize,
	minimize: FiMinimize,
	googleCalendar: BiLogoGoogle,
	briefcase: LuBriefcase,
	mail: FiMail,
	key: FiKey,
	friends: HiOutlineUserGroup,
	outlineShoppingBag: HiOutlineShoppingBag,
	outlinePrivacyTip: MdOutlinePrivacyTip,
	link: MdLink,
	googleLogo: FcGoogle,
	telegramLogo: FaTelegramPlane,
	globe: FaGlobe,
	calendarDays: LuCalendarDays,
	cameraPlus: TbCameraPlus,
	githubLogo: FaGithub,
	location: CiLocationOn,
	archive: GoArchive,
	wind: TbWind,
	cloudy: WiCloudy,
	humidity: WiHumidity,
	download: LuDownload,
	penAI: RiQuillPenAiLine,
	outlineDrag: AiOutlineDrag,
	outlineGlobe: HiOutlineGlobeAlt,
	outlineHome: HiOutlineHome,
	outlineSquares2X2: HiOutlineSquares2X2,
	squares2X2: HiSquares2X2,
	viewGridAdd: HiOutlineViewGridAdd,
	folderSpecial: MdFolderSpecial,
	history: LuHistory,
	mic: MdMic,
} satisfies IconMap
