import {
	FiAtSign,
	FiBell,
	FiClock,
	FiCoffee,
	FiFilter,
	FiGift,
	FiInbox,
	FiKey,
	FiLoader,
	FiLock,
	FiLogOut,
	FiMail,
	FiMaximize,
	FiMinimize,
	FiPhone,
	FiRefreshCw,
	FiRotateCcw,
	FiSave,
	FiSettings,
	FiShoppingBag,
	FiShoppingCart,
	FiTarget,
	FiTrash2,
	FiUser,
	FiUserCheck,
	FiUsers,
	FiUserX,
} from 'react-icons/fi'
import type { IconMap } from '../types'
import { TfiAlert, TfiBackRight, TfiCheck, TfiCup } from 'react-icons/tfi'
import {
	LuBriefcase,
	LuCalendarDays,
	LuChevronDown,
	LuChevronLeft,
	LuChevronRight,
	LuChevronUp,
	LuCopy,
	LuDownload,
	LuHeart,
	LuHistory,
	LuLayers,
	LuLayoutTemplate,
	LuMinus,
	LuPen,
	LuPlus,
	LuTicket,
	LuX,
} from 'react-icons/lu'
import {
	FaCoins,
	FaCrown,
	FaExternalLinkAlt,
	FaGithub,
	FaGlobe,
	FaGlobeAsia,
	FaImage,
	FaMoon,
	FaPaintBrush,
	FaSortAmountDown,
	FaSpinner,
	FaTelegramPlane,
	FaUserSecret,
} from 'react-icons/fa'
import {
	TbCloudOff,
	TbUsersPlus,
	TbBookmarkPlus,
	TbCameraPlus,
	TbPhotoPlus,
	TbWind,
	TbEdit,
	TbArrowsUpDown,
	TbCalendarUser,
	TbApps,
	TbNotebook,
	TbArrowsRightLeft,
	TbCloudUpload,
	TbInfinity,
} from 'react-icons/tb'
import {
	MdDragIndicator,
	MdFolderSpecial,
	MdLink,
	MdMic,
	MdOutlineFilterList,
	MdOutlineFilterListOff,
	MdOutlineNetworkWifi,
	MdOutlinePrivacyTip,
	MdOutlineVerifiedUser,
	MdOutlineWallpaper,
	MdPets,
	MdSearch,
} from 'react-icons/md'
import {
	HiBookmark,
	HiHome,
	HiOutlineBookmark,
	HiOutlineCurrencyBangladeshi,
	HiOutlineEye,
	HiOutlineEyeSlash,
	HiOutlineFire,
	HiOutlineFolder,
	HiOutlineGlobeAlt,
	HiOutlineHome,
	HiOutlineInbox,
	HiOutlineInformationCircle,
	HiOutlineNewspaper,
	HiOutlineShoppingBag,
	HiOutlineSquares2X2,
	HiOutlineUserGroup,
	HiOutlineVideoCamera,
	HiSquares2X2,
} from 'react-icons/hi2'
import { FaFolder, FaFolderOpen } from 'react-icons/fa'
import { GoArchive, GoKebabHorizontal, GoTasklist } from 'react-icons/go'
import { IoMdAddCircle, IoMdHelp } from 'react-icons/io'
import {
	FaArrowDownLong,
	FaArrowUpLong,
	FaExclamation,
	FaPhotoFilm,
	FaTreeCity,
} from 'react-icons/fa6'
import { BiCalendar, BiLogoGoogle, BiRss, BiWifi, BiWifiOff } from 'react-icons/bi'
import { FcGoogle } from 'react-icons/fc'
import { CiLocationOn, CiPause1 } from 'react-icons/ci'
import { WiCloudy, WiHumidity } from 'react-icons/wi'
import { RiApps2AiLine, RiQuillPenAiLine } from 'react-icons/ri'
import { AiOutlineCrown, AiOutlineDrag } from 'react-icons/ai'
import { HiOutlineViewGridAdd } from 'react-icons/hi'
import { BsFilterLeft, BsGenderAmbiguous } from 'react-icons/bs'
import { IoPricetagOutline } from 'react-icons/io5'
import { VscColorMode, VscMegaphone, VscPlay, VscRecordKeys } from 'react-icons/vsc'

function ProDiamondIcon(props: React.SVGProps<SVGSVGElement>) {
	return (
		<svg
			viewBox="0 0 140 109"
			fill="currentColor"
			width="1em"
			height="1em"
			{...props}
		>
			<path
				d="M 17,11 L 10,18 L 1,24 L 5,29 L 10,41 L 12,38 L 17,34 L 25,30 L 21,24 L 18,17 Z M 26,11 L 27,15 L 30,21 L 33,24 L 35,28 L 35,31 L 33,35 L 30,38 L 23,41 L 19,44 L 18,46 L 20,48 L 24,57 L 33,71 L 36,78 L 50,102 L 53,105 L 60,108 L 66,108 L 69,107 L 86,97 L 89,94 L 114,80 L 122,74 L 130,70 L 136,65 L 139,58 L 139,51 L 136,44 L 134,42 L 131,33 L 126,24 L 118,19 L 93,12 L 89,12 L 74,8 L 67,5 L 48,0 L 40,1 L 32,6 Z M 121,58 L 118,61 L 78,88 L 75,87 L 91,64 L 98,57 L 104,55 L 112,55 Z M 69,47 L 82,51 L 86,55 L 86,60 L 68,86 L 64,90 L 61,89 L 60,84 L 58,64 L 58,51 L 62,47 Z M 103,26 L 106,25 L 117,28 L 119,30 L 122,35 L 126,45 L 123,49 L 110,49 L 106,48 L 102,45 L 101,43 L 101,29 Z M 70,16 L 73,16 L 85,19 L 93,22 L 95,26 L 94,39 L 90,44 L 87,45 L 70,41 L 65,39 L 61,35 L 61,30 L 67,19 Z"
				fillRule="evenodd"
			/>
		</svg>
	)
}

export const defaultIcons = {
	home: HiHome,
	calendar: BiCalendar,
	settings: FiSettings,
	search: MdSearch,
	user: FiUser,
	clock: FiClock,
	notification: FiBell,
	alert: TfiAlert,
	check: TfiCheck,
	close: LuX,
	info: HiOutlineInformationCircle,
	externalLink: FaExternalLinkAlt,
	offline: TbCloudOff,
	chevronUp: LuChevronUp,
	chevronDown: LuChevronDown,
	chevronLeft: LuChevronLeft,
	chevronRight: LuChevronRight,
	lock: FiLock,
	verifyUser: MdOutlineVerifiedUser,
	outlineEye: HiOutlineEye,
	outlineEyeSlash: HiOutlineEyeSlash,
	trash: FiTrash2,
	spinner: FaSpinner,
	backRight: TfiBackRight,
	loader: FiLoader,
	usersPlus: TbUsersPlus,
	bookmarkPlus: TbBookmarkPlus,
	folder: FaFolder,
	folderOpen: FaFolderOpen,
	menuOption: GoKebabHorizontal,
	uploadImage: TbCloudUpload,
	image: FaImage,
	imagePlus: TbPhotoPlus,
	help: IoMdHelp,
	outlineBookmark: HiOutlineBookmark,
	outlineFolder: HiOutlineFolder,
	reload: FiRotateCcw,
	plus: LuPlus,
	pen: LuPen,
	users: FiUsers,
	userCheck: FiUserCheck,
	userX: FiUserX,
	outlineInbox: HiOutlineInbox,
	inbox: FiInbox,
	brush: FaPaintBrush,
	photoFilm: FaPhotoFilm,
	coin: FaCoins,
	shoppingCart: FiShoppingCart,
	shoppingBag: FiShoppingBag,
	maximize: FiMaximize,
	minimize: FiMinimize,
	googleCalendar: BiLogoGoogle,
	briefcase: LuBriefcase,
	mail: FiMail,
	key: FiKey,
	friends: HiOutlineUserGroup,
	outlineShoppingBag: HiOutlineShoppingBag,
	outlinePrivacyTip: MdOutlinePrivacyTip,
	link: MdLink,
	googleLogo: FcGoogle,
	telegramLogo: FaTelegramPlane,
	globe: FaGlobe,
	calendarDays: LuCalendarDays,
	cameraPlus: TbCameraPlus,
	githubLogo: FaGithub,
	location: CiLocationOn,
	archive: GoArchive,
	wind: TbWind,
	cloudy: WiCloudy,
	humidity: WiHumidity,
	download: LuDownload,
	penAI: RiQuillPenAiLine,
	outlineDrag: AiOutlineDrag,
	outlineGlobe: HiOutlineGlobeAlt,
	outlineHome: HiOutlineHome,
	outlineSquares2X2: HiOutlineSquares2X2,
	squares2X2: HiSquares2X2,
	viewGridAdd: HiOutlineViewGridAdd,
	folderSpecial: MdFolderSpecial,
	history: LuHistory,
	mic: MdMic,
	gender: BsGenderAmbiguous,
	phone: FiPhone,
	atSign: FiAtSign,
	outlineHeart: LuHeart,
	outlineAddCircle: IoMdAddCircle,
	treeCity: FaTreeCity,
	edit: TbEdit,
	target: FiTarget,
	logOut: FiLogOut,
	play: VscPlay,
	globeAsia: FaGlobeAsia,
	moon: FaMoon,
	outlineNewspaper: HiOutlineNewspaper,
	currency: HiOutlineCurrencyBangladeshi,
	rss: BiRss,
	tags: IoPricetagOutline,
	save: FiSave,
	sortDown: FaSortAmountDown,
	outlineFilterListOff: MdOutlineFilterListOff,
	outlineFilterList: MdOutlineFilterList,
	crown: FaCrown,
	outlineCrown: AiOutlineCrown,
	diamond: ProDiamondIcon,
	filterLeft: BsFilterLeft,
	upDown: TbArrowsUpDown,
	coffee: FiCoffee,
	refresh: FiRefreshCw,
	cup: TfiCup,
	pause: CiPause1,
	dragIndicator: MdDragIndicator,
	upLong: FaArrowUpLong,
	downLong: FaArrowDownLong,
	pets: MdPets,
	wigiPad: TbCalendarUser,
	appsPlus: TbApps,
	taskList: GoTasklist,
	strike: HiOutlineFire,
	notebook: TbNotebook,
	gift: FiGift,
	platforms: RiApps2AiLine,
	wallpapers: MdOutlineWallpaper,
	lastUpdate: VscMegaphone,
	shortcuts: VscRecordKeys,
	theme: VscColorMode,
	network: MdOutlineNetworkWifi,
	videoCamera: HiOutlineVideoCamera,
	advanced_ui: LuLayers,
	simple_ui: LuLayoutTemplate,
	arrowRightLeft: TbArrowsRightLeft,
	bookmark: HiBookmark,
	userSecret: FaUserSecret,
	filter: FiFilter,
	exclamation: FaExclamation,
	copy: LuCopy,
	wifi: BiWifi,
	wifiOff: BiWifiOff,
	infinity: TbInfinity,
	ticket: LuTicket,
	minus: LuMinus,
} satisfies IconMap
