import {
	FiAtSign,
	FiBell,
	FiClock,
	FiCoffee,
	FiFilter,
	FiGift,
	FiInbox,
	FiKey,
	FiLoader,
	FiLock,
	FiLogOut,
	FiMail,
	FiMaximize,
	FiMinimize,
	FiPhone,
	FiRefreshCw,
	FiRotateCcw,
	FiSave,
	FiSettings,
	FiShoppingBag,
	FiShoppingCart,
	FiTarget,
	FiTrash2,
	FiUser,
	FiUserCheck,
	FiUsers,
	FiUserX,
} from 'react-icons/fi'
import type { IconMap } from '../types'
import { TfiAlert, TfiBackRight, TfiCheck, TfiCup } from 'react-icons/tfi'
import {
	LuBriefcase,
	LuCalendarDays,
	LuChevronDown,
	LuChevronLeft,
	LuChevronRight,
	LuChevronUp,
	LuCopy,
	LuDownload,
	LuHeart,
	LuHistory,
	LuLayers,
	LuLayoutTemplate,
	LuMinus,
	LuPen,
	LuPlus,
	LuTicket,
	LuX,
} from 'react-icons/lu'
import {
	FaCoins,
	FaCrown,
	FaExternalLinkAlt,
	FaGithub,
	FaGlobe,
	FaGlobeAsia,
	FaImage,
	FaMoon,
	FaPaintBrush,
	FaSortAmountDown,
	FaSpinner,
	FaTelegramPlane,
	FaUserSecret,
} from 'react-icons/fa'
import {
	TbCloudOff,
	TbUsersPlus,
	TbBookmarkPlus,
	TbCameraPlus,
	TbPhotoPlus,
	TbWind,
	TbEdit,
	TbArrowsUpDown,
	TbCalendarUser,
	TbApps,
	TbNotebook,
	TbArrowsRightLeft,
	TbCloudUpload,
	TbInfinity,
} from 'react-icons/tb'
import {
	MdDragIndicator,
	MdFolderSpecial,
	MdLink,
	MdMic,
	MdOutlineFilterList,
	MdOutlineFilterListOff,
	MdOutlineNetworkWifi,
	MdOutlinePrivacyTip,
	MdOutlineVerifiedUser,
	MdOutlineWallpaper,
	MdPets,
	MdSearch,
} from 'react-icons/md'
import {
	HiBookmark,
	HiHome,
	HiOutlineBookmark,
	HiOutlineCurrencyBangladeshi,
	HiOutlineEye,
	HiOutlineEyeSlash,
	HiOutlineFire,
	HiOutlineFolder,
	HiOutlineGlobeAlt,
	HiOutlineHome,
	HiOutlineInbox,
	HiOutlineInformationCircle,
	HiOutlineNewspaper,
	HiOutlineShoppingBag,
	HiOutlineSquares2X2,
	HiOutlineUserGroup,
	HiOutlineVideoCamera,
	HiSquares2X2,
} from 'react-icons/hi2'
import { FaFolder, FaFolderOpen } from 'react-icons/fa'
import { GoArchive, GoKebabHorizontal, GoTasklist } from 'react-icons/go'
import { IoMdAddCircle, IoMdHelp } from 'react-icons/io'
import {
	FaArrowDownLong,
	FaArrowUpLong,
	FaExclamation,
	FaPhotoFilm,
	FaTreeCity,
} from 'react-icons/fa6'
import { BiCalendar, BiLogoGoogle, BiRss, BiWifi, BiWifiOff } from 'react-icons/bi'
import { FcGoogle } from 'react-icons/fc'
import { CiLocationOn, CiPause1 } from 'react-icons/ci'
import { WiCloudy, WiHumidity } from 'react-icons/wi'
import { RiApps2AiLine, RiQuillPenAiLine } from 'react-icons/ri'
import { AiOutlineCrown, AiOutlineDrag } from 'react-icons/ai'
import { HiOutlineViewGridAdd } from 'react-icons/hi'
import { BsFilterLeft, BsGenderAmbiguous } from 'react-icons/bs'
import { IoPricetagOutline } from 'react-icons/io5'
import { VscColorMode, VscMegaphone, VscPlay, VscRecordKeys } from 'react-icons/vsc'

function ProDiamondIcon(props: React.SVGProps<SVGSVGElement>) {
	return (
		<svg viewBox="0 0 24 24" fill="currentColor" width="1em" height="1em" {...props}>
			<path d="M4.9 6.2C4.9 7.4 4.3 8.3 3.1 8.4C4.3 8.5 4.9 9.4 4.9 10.6C5.0 9.4 5.6 8.5 6.8 8.4C5.6 8.3 5.0 7.4 4.9 6.2Z" />
			<path
				fillRule="evenodd"
				clipRule="evenodd"
				d="M8.2 5.3C8.6 4.9 9.3 4.8 9.8 5.1L20.4 11.2C21.0 11.6 21.2 12.3 20.9 12.9L11.7 18.7C11.2 19.0 10.6 19.0 10.1 18.6L5.4 11.8C5.0 11.2 5.1 10.4 5.7 9.9L8.2 5.3ZM11.8 7.3L14.6 8.1C14.8 8.2 15.0 8.4 14.9 8.7L14.3 10.1C14.2 10.3 14.0 10.4 13.7 10.4L11.2 9.8C10.9 9.7 10.8 9.4 10.9 9.1L11.3 7.6C11.4 7.4 11.6 7.2 11.8 7.3ZM16.3 8.6L18.5 9.9C18.7 10.0 18.8 10.3 18.6 10.5L17.6 11.0C17.4 11.1 17.2 11.0 17.0 10.9L15.6 9.8C15.4 9.6 15.4 9.3 15.6 9.1L15.9 8.7C16.0 8.6 16.2 8.5 16.3 8.6ZM10.9 11.3C11.1 11.2 11.4 11.3 11.5 11.5L13.6 12.3C13.8 12.4 13.9 12.6 13.8 12.8L12.2 16.0C12.0 16.3 11.6 16.3 11.4 16.1L10.7 12.0C10.6 11.7 10.7 11.4 10.9 11.3ZM14.6 12.3C14.8 12.2 15.1 12.2 15.3 12.3L18.1 12.7C18.4 12.7 18.5 13.0 18.3 13.2L13.8 15.7C13.5 15.8 13.3 15.6 13.4 15.3L14.3 12.6C14.4 12.4 14.5 12.3 14.6 12.3Z"
			/>
		</svg>
	)
}

export const defaultIcons = {
	home: HiHome,
	calendar: BiCalendar,
	settings: FiSettings,
	search: MdSearch,
	user: FiUser,
	clock: FiClock,
	notification: FiBell,
	alert: TfiAlert,
	check: TfiCheck,
	close: LuX,
	info: HiOutlineInformationCircle,
	externalLink: FaExternalLinkAlt,
	offline: TbCloudOff,
	chevronUp: LuChevronUp,
	chevronDown: LuChevronDown,
	chevronLeft: LuChevronLeft,
	chevronRight: LuChevronRight,
	lock: FiLock,
	verifyUser: MdOutlineVerifiedUser,
	outlineEye: HiOutlineEye,
	outlineEyeSlash: HiOutlineEyeSlash,
	trash: FiTrash2,
	spinner: FaSpinner,
	backRight: TfiBackRight,
	loader: FiLoader,
	usersPlus: TbUsersPlus,
	bookmarkPlus: TbBookmarkPlus,
	folder: FaFolder,
	folderOpen: FaFolderOpen,
	menuOption: GoKebabHorizontal,
	uploadImage: TbCloudUpload,
	image: FaImage,
	imagePlus: TbPhotoPlus,
	help: IoMdHelp,
	outlineBookmark: HiOutlineBookmark,
	outlineFolder: HiOutlineFolder,
	reload: FiRotateCcw,
	plus: LuPlus,
	pen: LuPen,
	users: FiUsers,
	userCheck: FiUserCheck,
	userX: FiUserX,
	outlineInbox: HiOutlineInbox,
	inbox: FiInbox,
	brush: FaPaintBrush,
	photoFilm: FaPhotoFilm,
	coin: FaCoins,
	shoppingCart: FiShoppingCart,
	shoppingBag: FiShoppingBag,
	maximize: FiMaximize,
	minimize: FiMinimize,
	googleCalendar: BiLogoGoogle,
	briefcase: LuBriefcase,
	mail: FiMail,
	key: FiKey,
	friends: HiOutlineUserGroup,
	outlineShoppingBag: HiOutlineShoppingBag,
	outlinePrivacyTip: MdOutlinePrivacyTip,
	link: MdLink,
	googleLogo: FcGoogle,
	telegramLogo: FaTelegramPlane,
	globe: FaGlobe,
	calendarDays: LuCalendarDays,
	cameraPlus: TbCameraPlus,
	githubLogo: FaGithub,
	location: CiLocationOn,
	archive: GoArchive,
	wind: TbWind,
	cloudy: WiCloudy,
	humidity: WiHumidity,
	download: LuDownload,
	penAI: RiQuillPenAiLine,
	outlineDrag: AiOutlineDrag,
	outlineGlobe: HiOutlineGlobeAlt,
	outlineHome: HiOutlineHome,
	outlineSquares2X2: HiOutlineSquares2X2,
	squares2X2: HiSquares2X2,
	viewGridAdd: HiOutlineViewGridAdd,
	folderSpecial: MdFolderSpecial,
	history: LuHistory,
	mic: MdMic,
	gender: BsGenderAmbiguous,
	phone: FiPhone,
	atSign: FiAtSign,
	outlineHeart: LuHeart,
	outlineAddCircle: IoMdAddCircle,
	treeCity: FaTreeCity,
	edit: TbEdit,
	target: FiTarget,
	logOut: FiLogOut,
	play: VscPlay,
	globeAsia: FaGlobeAsia,
	moon: FaMoon,
	outlineNewspaper: HiOutlineNewspaper,
	currency: HiOutlineCurrencyBangladeshi,
	rss: BiRss,
	tags: IoPricetagOutline,
	save: FiSave,
	sortDown: FaSortAmountDown,
	outlineFilterListOff: MdOutlineFilterListOff,
	outlineFilterList: MdOutlineFilterList,
	crown: FaCrown,
	outlineCrown: AiOutlineCrown,
	diamond: ProDiamondIcon,
	filterLeft: BsFilterLeft,
	upDown: TbArrowsUpDown,
	coffee: FiCoffee,
	refresh: FiRefreshCw,
	cup: TfiCup,
	pause: CiPause1,
	dragIndicator: MdDragIndicator,
	upLong: FaArrowUpLong,
	downLong: FaArrowDownLong,
	pets: MdPets,
	wigiPad: TbCalendarUser,
	appsPlus: TbApps,
	taskList: GoTasklist,
	strike: HiOutlineFire,
	notebook: TbNotebook,
	gift: FiGift,
	platforms: RiApps2AiLine,
	wallpapers: MdOutlineWallpaper,
	lastUpdate: VscMegaphone,
	shortcuts: VscRecordKeys,
	theme: VscColorMode,
	network: MdOutlineNetworkWifi,
	videoCamera: HiOutlineVideoCamera,
	advanced_ui: LuLayers,
	simple_ui: LuLayoutTemplate,
	arrowRightLeft: TbArrowsRightLeft,
	bookmark: HiBookmark,
	userSecret: FaUserSecret,
	filter: FiFilter,
	exclamation: FaExclamation,
	copy: LuCopy,
	wifi: BiWifi,
	wifiOff: BiWifiOff,
	infinity: TbInfinity,
	ticket: LuTicket,
	minus: LuMinus,
} satisfies IconMap
