import { WidgetKeys } from '../layout-engine/types'
import type { PresetLayout } from './types'

export const PRESET_LAYOUTS: PresetLayout[] = [
	{
		id: 'default',
		title: 'چیدمان پیش‌فرض',
		description: 'چیدمان استاندارد و کامل ویجتیفای با دسترسی به تمام ابزارها',
		isVip: false,
		isFeatured: true,
		category: 'daily',
		widgets: [
			{
				id: WidgetKeys.wigiPad,
				instanceId: 'wigipad-default',
				position: { col: 0, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'search-default',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'bookmarks-default',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.widgetify,
				instanceId: 'widgetify-default',
				position: { col: 6, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.comboWidget,
				instanceId: 'combo-widget-default',
				position: { col: 0, row: 3 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.yadKar,
				instanceId: 'yadkar-default',
				position: { col: 2, row: 3 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'tools-default',
				position: { col: 4, row: 3 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'calendar-default',
				position: { col: 6, row: 3 },
				size: { w: 2, h: 3 },
			},
		],
	},
	{
		id: 'zen-breath',
		title: 'آرامش ذهن',
		description: 'خلوت و مینیمال برای آرامش ذهن و کاهش بار شناختی',
		isVip: false,
		isFeatured: true,
		category: 'minimal',
		verticalAlign: 'center',
		widgets: [
			{
				id: WidgetKeys.calendar,
				instanceId: 'zen-calendar',
				position: { col: 2, row: 0 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'zen-clock',
				position: { col: 3, row: 0 },
				size: { w: 2, h: 1 },
				meta: { variant: 'digital' },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'zen-search',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 1 },
			},
		],
	},
	{
		id: 'deep-work',
		title: 'تمرکز عمیق',
		description: 'نمایش تسک‌ها و یادداشت‌ها برای شروع کار بدون حواس‌پرتی',
		isVip: false,
		isFeatured: true,
		category: 'productivity',
		widgets: [
			{
				id: WidgetKeys.clock,
				instanceId: 'deep-clock',
				position: { col: 2, row: 0 },
				size: { w: 2, h: 1 },
				meta: { variant: 'digital' },
			},
			{
				id: WidgetKeys.HabitTracker,
				instanceId: 'deep-habit',
				position: { col: 4, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.todos,
				instanceId: 'deep-todos',
				position: { col: 2, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'deep-notes',
				position: { col: 4, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'deep-search',
				position: { col: 2, row: 4 },
				size: { w: 4, h: 1 },
			},
		],
	},
	{
		id: 'morning-briefing',
		title: 'داشبورد صبحگاهی',
		description: 'مرور سریع زمان، تقویم، هوا و بوکمارک‌ها در چند ثانیه',
		isVip: false,
		isFeatured: true,
		category: 'daily',
		widgets: [
			{
				id: WidgetKeys.wigiPad,
				instanceId: 'briefing-wigipad',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'briefing-search',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'briefing-bookmarks',
				position: { col: 2, row: 2 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.weather,
				instanceId: 'briefing-weather',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 3 },
			},
		],
	},
	{
		id: 'glass-typography',
		title: 'تایپوگرافی شیشه‌ای',
		description: 'ساعت یخی بزرگ و المان‌های شیشه‌ای اشرافی',
		isVip: true,
		isFeatured: true,
		category: 'minimal',
		widgets: [
			{
				id: WidgetKeys.moodTracker,
				instanceId: 'glass-mood',
				position: { col: 0, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.transparentClock,
				instanceId: 'glass-clock',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 2 },
				meta: { variant: 'persian' },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'glass-search',
				position: { col: 6, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'glass-notes',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 2 },
				meta: { variant: 'sticky' },
			},
			{
				id: WidgetKeys.arzLive,
				instanceId: 'glass-arz',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 2 },
				meta: { variant: 'stacked' },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'glass-bookmarks',
				position: { col: 2, row: 2 },
				size: { w: 2, h: 2 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'glass-flip-clock',
				position: { col: 4, row: 2 },
				size: { w: 2, h: 1 },
				meta: { variant: 'flip' },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'glass-cal',
				position: { col: 6, row: 3 },
				size: { w: 2, h: 1 },
			},
		],
	},
	{
		id: 'financial-cockpit',
		title: 'کاکپیت بازارهای مالی',
		description: 'مانیتورینگ ارزها، نوت‌های فوری، پومودورو و شبکه',
		isVip: true,
		isFeatured: true,
		category: 'finance',
		widgets: [
			{
				id: WidgetKeys.arzLive,
				instanceId: 'fin-arz',
				position: { col: 0, row: 0 },
				size: { w: 2, h: 2 },
				meta: { variant: 'stacked' },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'fin-search',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'fin-bookmarks',
				position: { col: 6, row: 0 },
				size: { w: 2, h: 2 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'fin-clock',
				position: { col: 2, row: 1 },
				size: { w: 2, h: 1 },
				meta: { variant: 'flip' },
			},
			{
				id: WidgetKeys.moodTracker,
				instanceId: 'fin-mood',
				position: { col: 4, row: 1 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.network,
				instanceId: 'fin-net',
				position: { col: 0, row: 2 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'fin-notes',
				position: { col: 2, row: 2 },
				size: { w: 2, h: 2 },
				meta: { variant: 'sticky' },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'fin-tools',
				position: { col: 4, row: 2 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.weather,
				instanceId: 'fin-weather',
				position: { col: 6, row: 2 },
				size: { w: 2, h: 1 },
			},
		],
	},
	{
		id: 'habit-momentum',
		title: 'حلقه عادت‌ها',
		description: 'ثبت و پیگیری مداوم زنجیره عادات روزانه',
		isVip: false,
		isFeatured: false,
		category: 'productivity',
		widgets: [
			{
				id: WidgetKeys.HabitTracker,
				instanceId: 'habit-tracker',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.yadKar,
				instanceId: 'habit-yadkar',
				position: { col: 2, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'habit-search',
				position: { col: 4, row: 1 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'habit-bookmarks',
				position: { col: 4, row: 2 },
				size: { w: 4, h: 2 },
			},
		],
	},
	{
		id: 'navigator-hub',
		title: 'ایستگاه ناوبری',
		description: 'دسترسی سریع به نشانک‌ها، سرچ و ویجت ترکیبی',
		isVip: false,
		isFeatured: false,
		category: 'daily',
		widgets: [
			{
				id: WidgetKeys.clock,
				instanceId: 'nav-clock',
				position: { col: 0, row: 1 },
				size: { w: 1, h: 1 },
				meta: { variant: 'digital-vertical' },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'nav-cal',
				position: { col: 1, row: 1 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'nav-search',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'nav-bookmarks',
				position: { col: 2, row: 2 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.comboWidget,
				instanceId: 'nav-combo',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 3 },
			},
		],
	},
	{
		id: 'study-station',
		title: 'میز مطالعه و یادگیری',
		description: '۴ ستون منظم برای یادداشت، کارها، ابزارها و تقویم',
		isVip: false,
		isFeatured: false,
		category: 'productivity',
		widgets: [
			{
				id: WidgetKeys.notes,
				instanceId: 'study-notes',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.todos,
				instanceId: 'study-todos',
				position: { col: 2, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'study-tools',
				position: { col: 4, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'study-cal',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 3 },
			},
		],
	},
	{
		id: 'cozy-companion',
		title: 'روزمرگی گرم و با‌نشاط',
		description: 'حضور پت و کاراکتر مجازی در کنار ابزارهای اصلی',
		isVip: false,
		isFeatured: false,
		category: 'lifestyle',
		verticalAlign: 'bottom',
		widgets: [
			{
				id: WidgetKeys.widgetify,
				instanceId: 'cozy-widgetify',
				position: { col: 1, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'cozy-search',
				position: { col: 3, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'cozy-bookmarks',
				position: { col: 3, row: 1 },
				size: { w: 4, h: 2 },
			},
		],
	},
	{
		id: 'dev-architect',
		title: 'معمار توسعه‌دهنده',
		description: 'فضای عریض کارهای فنی، وضعیت پینگ، شبکه و پومودورو',
		isVip: true,
		isFeatured: false,
		category: 'productivity',
		widgets: [
			{
				id: WidgetKeys.search,
				instanceId: 'dev-search',
				position: { col: 0, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'dev-clock',
				position: { col: 4, row: 0 },
				size: { w: 2, h: 1 },
				meta: { variant: 'flip' },
			},
			{
				id: WidgetKeys.network,
				instanceId: 'dev-net',
				position: { col: 6, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.todos,
				instanceId: 'dev-todos',
				position: { col: 0, row: 1 },
				size: { w: 4, h: 3 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'dev-bookmarks',
				position: { col: 4, row: 1 },
				size: { w: 2, h: 2 },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'dev-tools',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.weather,
				instanceId: 'dev-weather',
				position: { col: 6, row: 2 },
				size: { w: 2, h: 1 },
			},
		],
	},
	{
		id: 'mindful-living',
		title: 'رشد و خودآگاهی',
		description: 'ثبت حال روحی، استیک نوت و پایش عادات روزمره',
		isVip: true,
		isFeatured: false,
		category: 'lifestyle',
		widgets: [
			{
				id: WidgetKeys.moodTracker,
				instanceId: 'mind-mood',
				position: { col: 1, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'mind-clock',
				position: { col: 3, row: 0 },
				size: { w: 1, h: 1 },
				meta: { variant: 'analog' },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'mind-cal',
				position: { col: 4, row: 0 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.weather,
				instanceId: 'mind-weather',
				position: { col: 5, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'mind-notes',
				position: { col: 1, row: 1 },
				size: { w: 2, h: 2 },
				meta: { variant: 'sticky' },
			},
			{
				id: WidgetKeys.HabitTracker,
				instanceId: 'mind-habit',
				position: { col: 3, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'mind-bookmarks',
				position: { col: 5, row: 1 },
				size: { w: 2, h: 2 },
			},
		],
	},
	{
		id: 'nordic-studio',
		title: 'استودیو نوردیک',
		description: 'سادگی فوق‌العاده با المان‌های نواری و فضای خالی باز',
		isVip: true,
		isFeatured: false,
		category: 'minimal',
		verticalAlign: 'center',
		widgets: [
			{
				id: WidgetKeys.clock,
				instanceId: 'nordic-clock',
				position: { col: 1, row: 0 },
				size: { w: 1, h: 1 },
				meta: { variant: 'analog' },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'nordic-cal',
				position: { col: 2, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'nordic-search',
				position: { col: 4, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.weather,
				instanceId: 'nordic-weather',
				position: { col: 6, row: 0 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'nordic-bookmarks',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 1 },
			},
		],
	},
	{
		id: 'editorial-pulse',
		title: 'پالس رسانه‌ای',
		description: 'تفکیک ستونی برای مطالعه متمرکز اخبار و ارز',
		isVip: true,
		isFeatured: false,
		category: 'daily',
		widgets: [
			{
				id: WidgetKeys.news,
				instanceId: 'edit-news',
				position: { col: 0, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.arzLive,
				instanceId: 'edit-arz',
				position: { col: 2, row: 0 },
				size: { w: 2, h: 2 },
				meta: { variant: 'stacked' },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'edit-clock',
				position: { col: 2, row: 2 },
				size: { w: 2, h: 1 },
				meta: { variant: 'flip' },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'edit-search',
				position: { col: 4, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'edit-bookmarks',
				position: { col: 4, row: 1 },
				size: { w: 4, h: 2 },
			},
		],
	},
	{
		id: 'executive-life-os',
		title: 'اتاق فرمان زندگی',
		description: 'داشبورد ۴ ستونه متوازن برای کار، زمان، پول و یادداشت',
		isVip: true,
		isFeatured: false,
		category: 'daily',
		widgets: [
			{
				id: WidgetKeys.wigiPad,
				instanceId: 'exec-wigipad',
				position: { col: 0, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.todos,
				instanceId: 'exec-todos',
				position: { col: 2, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'exec-notes',
				position: { col: 4, row: 0 },
				size: { w: 2, h: 2 },
				meta: { variant: 'sticky' },
			},
			{
				id: WidgetKeys.moodTracker,
				instanceId: 'exec-mood',
				position: { col: 4, row: 2 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.arzLive,
				instanceId: 'exec-arz',
				position: { col: 6, row: 0 },
				size: { w: 2, h: 2 },
				meta: { variant: 'stacked' },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'exec-tools',
				position: { col: 6, row: 2 },
				size: { w: 2, h: 1 },
			},
		],
	},
]
