import { WidgetKeys } from '../layout-engine/types'
import type { PresetLayout } from './types'

export const PRESET_LAYOUTS: PresetLayout[] = [
	{
		id: 'default',
		title: 'چیدمان پیش‌فرض',
		description: 'چیدمان استاندارد و کامل ویجتیفای با دسترسی به تمام ابزارها',
		isVip: false,
		isFeatured: true,
		category: 'daily',
		widgets: [
			{
				id: WidgetKeys.wigiPad,
				instanceId: 'wigipad-default',
				position: { col: 0, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'search-default',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'bookmarks-default',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.widgetify,
				instanceId: 'widgetify-default',
				position: { col: 6, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.comboWidget,
				instanceId: 'combo-widget-default',
				position: { col: 0, row: 3 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.yadKar,
				instanceId: 'yadkar-default',
				position: { col: 2, row: 3 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'tools-default',
				position: { col: 4, row: 3 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'calendar-default',
				position: { col: 6, row: 3 },
				size: { w: 2, h: 3 },
			},
		],
	},
	{
		id: 'simple-appearance',
		title: 'ظاهری ساده',
		description: 'جستجوی بالا و ابزارهای متمرکز در پایین صفحه',
		isVip: false,
		isFeatured: true,
		category: 'daily',
		verticalAlign: 'split-bottom',
		widgets: [
			{
				id: WidgetKeys.search,
				instanceId: 'search-simple',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'clock-simple',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 1 },
				meta: { variant: 'digital' },
			},
			{
				id: WidgetKeys.moodTracker,
				instanceId: 'moodtracker-simple',
				position: { col: 0, row: 2 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'calendar-simple',
				position: { col: 1, row: 2 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.HabitTracker,
				instanceId: 'habittracker-simple',
				position: { col: 0, row: 3 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'bookmarks-simple',
				position: { col: 2, row: 2 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.yadKar,
				instanceId: 'yadkar-simple',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 3 },
			},
		],
	},
	{
		id: 'zen-minimal',
		title: 'آرامش و سادگی',
		description: 'کاهش حداکثری شلوغی با ساعت، تقویم و جستجوی وسط‌چین',
		isVip: false,
		isFeatured: true,
		category: 'minimal',
		verticalAlign: 'center',
		widgets: [
			{
				id: WidgetKeys.calendar,
				instanceId: 'zen-calendar',
				position: { col: 2, row: 0 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'zen-clock',
				position: { col: 3, row: 0 },
				size: { w: 2, h: 1 },
				meta: { variant: 'digital' },
			},
			{
				id: WidgetKeys.HabitTracker,
				instanceId: 'zen-habit',
				position: { col: 5, row: 0 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'zen-search',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'zen-bookmarks',
				position: { col: 2, row: 2 },
				size: { w: 4, h: 2 },
			},
		],
	},
	{
		id: 'deep-work-flow',
		title: 'تمرکز کاری و تسک‌ها',
		description: 'مدیریت وظایف روزانه، یادداشت‌ها، تقویم و ابزارها برای کار عمیق',
		isVip: false,
		isFeatured: true,
		category: 'productivity',
		widgets: [
			{
				id: WidgetKeys.clock,
				instanceId: 'work-clock',
				position: { col: 0, row: 0 },
				size: { w: 2, h: 1 },
				meta: { variant: 'digital' },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'work-search',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.HabitTracker,
				instanceId: 'work-habit',
				position: { col: 6, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.todos,
				instanceId: 'work-todos',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'work-notes',
				position: { col: 2, row: 1 },
				size: { w: 2, h: 3 },
				meta: { variant: 'list' },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'work-bookmarks',
				position: { col: 4, row: 1 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'work-calendar',
				position: { col: 4, row: 3 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'work-tools',
				position: { col: 6, row: 3 },
				size: { w: 2, h: 3 },
			},
		],
	},
	{
		id: 'crypto-finance-hub',
		title: 'مرکز ترید و ارز دیجیتال',
		description: 'قیمت‌های زنده بازار، نرخ لحظه‌ای ارزها، وضعیت پینگ و ابزارها',
		isVip: true,
		isFeatured: true,
		category: 'finance',
		verticalAlign: 'split-bottom',
		widgets: [
			{
				id: WidgetKeys.search,
				instanceId: 'crypto-search',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.arzLive,
				instanceId: 'crypto-arz-live',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 3 },
				meta: { variant: 'stacked' },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'crypto-bookmarks',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'crypto-clock',
				position: { col: 2, row: 3 },
				size: { w: 2, h: 1 },
				meta: { variant: 'flip' },
			},
			{
				id: WidgetKeys.network,
				instanceId: 'crypto-network',
				position: { col: 4, row: 3 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.news,
				instanceId: 'crypto-news',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 3 },
			},
		],
	},
	{
		id: 'developer-cockpit',
		title: 'میز کار برنامه‌نویس',
		description: 'تودوهای عریض، پینگ سرور، یادداشت استیکی و بوکمارک‌های دم‌دست',
		isVip: true,
		isFeatured: false,
		category: 'productivity',
		widgets: [
			{
				id: WidgetKeys.search,
				instanceId: 'dev-search',
				position: { col: 0, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'dev-clock',
				position: { col: 4, row: 0 },
				size: { w: 2, h: 1 },
				meta: { variant: 'flip' },
			},
			{
				id: WidgetKeys.network,
				instanceId: 'dev-net',
				position: { col: 6, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.todos,
				instanceId: 'dev-todos',
				position: { col: 0, row: 1 },
				size: { w: 4, h: 3 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'dev-bookmarks',
				position: { col: 4, row: 1 },
				size: { w: 2, h: 2 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'dev-notes',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 2 },
				meta: { variant: 'sticky' },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'dev-tools',
				position: { col: 4, row: 3 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.weather,
				instanceId: 'dev-weather',
				position: { col: 6, row: 3 },
				size: { w: 2, h: 1 },
			},
		],
	},
	{
		id: 'habit-mindfulness',
		title: 'سلامت روان و عادات',
		description: 'ثبت حال روحی، پیگیری مستمر عادت‌ها و حیوان خانگی همراه',
		isVip: true,
		isFeatured: false,
		category: 'lifestyle',
		widgets: [
			{
				id: WidgetKeys.clock,
				instanceId: 'mind-clock',
				position: { col: 0, row: 0 },
				size: { w: 2, h: 1 },
				meta: { variant: 'analog' },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'mind-search',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.weather,
				instanceId: 'mind-weather',
				position: { col: 6, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.HabitTracker,
				instanceId: 'mind-habit',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'mind-notes',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 2 },
				meta: { variant: 'sticky' },
			},
			{
				id: WidgetKeys.moodTracker,
				instanceId: 'mind-mood',
				position: { col: 2, row: 3 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.pet,
				instanceId: 'mind-pet',
				position: { col: 4, row: 3 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'mind-cal',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 3 },
			},
		],
	},
]
