import { WidgetKeys } from '../layout-engine/types'
import type { PresetLayout } from './types'

export const PRESET_LAYOUTS: PresetLayout[] = [
	{
		id: 'default',
		title: 'چیدمان پیش‌فرض',
		description: 'چیدمان استاندارد و کامل ویجتیفای با دسترسی به تمام ابزارها',
		isVip: false,
		isFeatured: true,
		category: 'daily',
		widgets: [
			{
				id: WidgetKeys.wigiPad,
				instanceId: 'wigipad-default',
				position: { col: 0, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'search-default',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'bookmarks-default',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.widgetify,
				instanceId: 'widgetify-default',
				position: { col: 6, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.comboWidget,
				instanceId: 'combo-widget-default',
				position: { col: 0, row: 3 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.yadKar,
				instanceId: 'yadkar-default',
				position: { col: 2, row: 3 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'tools-default',
				position: { col: 4, row: 3 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'calendar-default',
				position: { col: 6, row: 3 },
				size: { w: 2, h: 3 },
			},
		],
	},
	{
		id: 'simple-appearance',
		title: 'ظاهری ساده',
		description: 'جستجوی بالا و ابزارهای متمرکز در پایین صفحه',
		isVip: false,
		isFeatured: true,
		category: 'daily',
		verticalAlign: 'split-bottom',
		widgets: [
			{
				id: WidgetKeys.search,
				instanceId: 'search-simple',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'clock-simple',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 1 },
				meta: { variant: 'digital' },
			},
			{
				id: WidgetKeys.moodTracker,
				instanceId: 'moodtracker-simple',
				position: { col: 0, row: 2 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'calendar-simple',
				position: { col: 1, row: 2 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.HabitTracker,
				instanceId: 'habittracker-simple',
				position: { col: 0, row: 3 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'bookmarks-simple',
				position: { col: 2, row: 2 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.yadKar,
				instanceId: 'yadkar-simple',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 3 },
			},
		],
	},
	{
		id: 'focus-horizon',
		title: 'افق تمرکز',
		description: 'جستجوی بالا با تسک‌ها، یادداشت، زمان و بوکمارک‌ها در پایین',
		isVip: false,
		isFeatured: true,
		category: 'productivity',
		verticalAlign: 'split-bottom',
		widgets: [
			{
				id: WidgetKeys.search,
				instanceId: 'search-focus',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.todos,
				instanceId: 'todos-focus',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'bookmarks-focus',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'clock-focus',
				position: { col: 2, row: 3 },
				size: { w: 2, h: 1 },
				meta: { variant: 'digital' },
			},
			{
				id: WidgetKeys.HabitTracker,
				instanceId: 'habittracker-focus',
				position: { col: 4, row: 3 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'notes-focus',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 3 },
			},
		],
	},
	{
		id: 'peaceful-dock',
		title: 'ایستگاه آرامش',
		description: 'خلوت و چشم‌نواز با دسترسی سریع به ویجت‌های اصلی در کف صفحه',
		isVip: false,
		isFeatured: true,
		category: 'daily',
		verticalAlign: 'split-bottom',
		widgets: [
			{
				id: WidgetKeys.search,
				instanceId: 'search-peaceful',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.wigiPad,
				instanceId: 'wigipad-peaceful',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'bookmarks-peaceful',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.moodTracker,
				instanceId: 'moodtracker-peaceful',
				position: { col: 2, row: 3 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'calendar-peaceful',
				position: { col: 3, row: 3 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'clock-peaceful',
				position: { col: 4, row: 3 },
				size: { w: 2, h: 1 },
				meta: { variant: 'digital' },
			},
			{
				id: WidgetKeys.weather,
				instanceId: 'weather-peaceful',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 3 },
			},
		],
	},
	{
		id: 'zen-breath',
		title: 'آرامش ذهن',
		description: 'خلوت و مینیمال برای آرامش ذهن و کاهش بار شناختی',
		isVip: false,
		isFeatured: true,
		category: 'minimal',
		verticalAlign: 'center',
		widgets: [
			{
				id: WidgetKeys.calendar,
				instanceId: 'zen-calendar',
				position: { col: 2, row: 0 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'zen-clock',
				position: { col: 3, row: 0 },
				size: { w: 2, h: 1 },
				meta: { variant: 'digital' },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'zen-search',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 1 },
			},
		],
	},
	{
		id: 'deep-work',
		title: 'تمرکز عمیق',
		description: 'نمایش تسک‌ها و یادداشت‌ها برای شروع کار بدون حواس‌پرتی',
		isVip: false,
		isFeatured: true,
		category: 'productivity',
		widgets: [
			{
				id: WidgetKeys.clock,
				instanceId: 'deep-clock',
				position: { col: 2, row: 0 },
				size: { w: 2, h: 1 },
				meta: { variant: 'digital' },
			},
			{
				id: WidgetKeys.HabitTracker,
				instanceId: 'deep-habit',
				position: { col: 4, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.todos,
				instanceId: 'deep-todos',
				position: { col: 2, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'deep-notes',
				position: { col: 4, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'deep-search',
				position: { col: 2, row: 4 },
				size: { w: 4, h: 1 },
			},
		],
	},

	{
		id: 'glass-typography',
		title: 'تایپوگرافی شیشه‌ای',
		description: 'ساعت ورقه‌ای، استیک نوت و ابزارهای پرمیوم در کف صفحه',
		isVip: true,
		isFeatured: true,
		category: 'minimal',
		verticalAlign: 'split-bottom',
		widgets: [
			{
				id: WidgetKeys.search,
				instanceId: 'glass-search',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'glass-notes',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 2 },
				meta: { variant: 'sticky' },
			},
			{
				id: WidgetKeys.moodTracker,
				instanceId: 'glass-mood',
				position: { col: 0, row: 3 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'glass-bookmarks',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'glass-flip-clock',
				position: { col: 2, row: 3 },
				size: { w: 2, h: 1 },
				meta: { variant: 'flip' },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'glass-cal',
				position: { col: 4, row: 3 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.arzLive,
				instanceId: 'glass-arz',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 2 },
				meta: { variant: 'stacked' },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'glass-tools',
				position: { col: 6, row: 3 },
				size: { w: 2, h: 1 },
			},
		],
	},
	{
		id: 'financial-cockpit',
		title: 'کاکپیت بازارهای مالی',
		description: 'مانیتورینگ زنده ارزها، پینگ شبکه، ساعت ورقه‌ای و یادداشت‌ها',
		isVip: true,
		isFeatured: true,
		category: 'finance',
		verticalAlign: 'split-bottom',
		widgets: [
			{
				id: WidgetKeys.search,
				instanceId: 'fin-search',
				position: { col: 2, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.arzLive,
				instanceId: 'fin-arz',
				position: { col: 0, row: 1 },
				size: { w: 2, h: 2 },
				meta: { variant: 'stacked' },
			},
			{
				id: WidgetKeys.network,
				instanceId: 'fin-net',
				position: { col: 0, row: 3 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'fin-bookmarks',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 2 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'fin-clock',
				position: { col: 2, row: 3 },
				size: { w: 2, h: 1 },
				meta: { variant: 'flip' },
			},
			{
				id: WidgetKeys.weather,
				instanceId: 'fin-weather',
				position: { col: 4, row: 3 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'fin-notes',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 2 },
				meta: { variant: 'sticky' },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'fin-tools',
				position: { col: 6, row: 3 },
				size: { w: 2, h: 1 },
			},
		],
	},


	{
		id: 'dev-architect',
		title: 'معمار توسعه‌دهنده',
		description: 'فضای عریض کارهای فنی، وضعیت پینگ، شبکه و پومودورو',
		isVip: true,
		isFeatured: false,
		category: 'productivity',
		widgets: [
			{
				id: WidgetKeys.search,
				instanceId: 'dev-search',
				position: { col: 0, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'dev-clock',
				position: { col: 4, row: 0 },
				size: { w: 2, h: 1 },
				meta: { variant: 'flip' },
			},
			{
				id: WidgetKeys.network,
				instanceId: 'dev-net',
				position: { col: 6, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.todos,
				instanceId: 'dev-todos',
				position: { col: 0, row: 1 },
				size: { w: 4, h: 3 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'dev-bookmarks',
				position: { col: 4, row: 1 },
				size: { w: 2, h: 2 },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'dev-tools',
				position: { col: 6, row: 1 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.weather,
				instanceId: 'dev-weather',
				position: { col: 6, row: 2 },
				size: { w: 2, h: 1 },
			},
		],
	},
	{
		id: 'mindful-living',
		title: 'رشد و خودآگاهی',
		description: 'ثبت حال روحی، استیک نوت و پایش عادات روزمره',
		isVip: true,
		isFeatured: false,
		category: 'lifestyle',
		widgets: [
			{
				id: WidgetKeys.moodTracker,
				instanceId: 'mind-mood',
				position: { col: 1, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'mind-clock',
				position: { col: 3, row: 0 },
				size: { w: 1, h: 1 },
				meta: { variant: 'analog' },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'mind-cal',
				position: { col: 4, row: 0 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.weather,
				instanceId: 'mind-weather',
				position: { col: 5, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'mind-notes',
				position: { col: 1, row: 1 },
				size: { w: 2, h: 2 },
				meta: { variant: 'sticky' },
			},
			{
				id: WidgetKeys.HabitTracker,
				instanceId: 'mind-habit',
				position: { col: 3, row: 1 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'mind-bookmarks',
				position: { col: 5, row: 1 },
				size: { w: 2, h: 2 },
			},
		],
	},
	{
		id: 'nordic-studio',
		title: 'استودیو نوردیک',
		description: 'سادگی فوق‌العاده با المان‌های نواری و فضای خالی باز',
		isVip: true,
		isFeatured: false,
		category: 'minimal',
		verticalAlign: 'center',
		widgets: [
			{
				id: WidgetKeys.clock,
				instanceId: 'nordic-clock',
				position: { col: 1, row: 0 },
				size: { w: 1, h: 1 },
				meta: { variant: 'analog' },
			},
			{
				id: WidgetKeys.calendar,
				instanceId: 'nordic-cal',
				position: { col: 2, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'nordic-search',
				position: { col: 4, row: 0 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.weather,
				instanceId: 'nordic-weather',
				position: { col: 6, row: 0 },
				size: { w: 1, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'nordic-bookmarks',
				position: { col: 2, row: 1 },
				size: { w: 4, h: 1 },
			},
		],
	},
	{
		id: 'editorial-pulse',
		title: 'پالس رسانه‌ای',
		description: 'تفکیک ستونی برای مطالعه متمرکز اخبار و ارز',
		isVip: true,
		isFeatured: false,
		category: 'daily',
		widgets: [
			{
				id: WidgetKeys.news,
				instanceId: 'edit-news',
				position: { col: 0, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.arzLive,
				instanceId: 'edit-arz',
				position: { col: 2, row: 0 },
				size: { w: 2, h: 2 },
				meta: { variant: 'stacked' },
			},
			{
				id: WidgetKeys.clock,
				instanceId: 'edit-clock',
				position: { col: 2, row: 2 },
				size: { w: 2, h: 1 },
				meta: { variant: 'flip' },
			},
			{
				id: WidgetKeys.search,
				instanceId: 'edit-search',
				position: { col: 4, row: 0 },
				size: { w: 4, h: 1 },
			},
			{
				id: WidgetKeys.bookmarks,
				instanceId: 'edit-bookmarks',
				position: { col: 4, row: 1 },
				size: { w: 4, h: 2 },
			},
		],
	},
	{
		id: 'executive-life-os',
		title: 'اتاق فرمان زندگی',
		description: 'داشبورد ۴ ستونه متوازن برای کار، زمان، پول و یادداشت',
		isVip: true,
		isFeatured: false,
		category: 'daily',
		widgets: [
			{
				id: WidgetKeys.wigiPad,
				instanceId: 'exec-wigipad',
				position: { col: 0, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.todos,
				instanceId: 'exec-todos',
				position: { col: 2, row: 0 },
				size: { w: 2, h: 3 },
			},
			{
				id: WidgetKeys.notes,
				instanceId: 'exec-notes',
				position: { col: 4, row: 0 },
				size: { w: 2, h: 2 },
				meta: { variant: 'sticky' },
			},
			{
				id: WidgetKeys.moodTracker,
				instanceId: 'exec-mood',
				position: { col: 4, row: 2 },
				size: { w: 2, h: 1 },
			},
			{
				id: WidgetKeys.arzLive,
				instanceId: 'exec-arz',
				position: { col: 6, row: 0 },
				size: { w: 2, h: 2 },
				meta: { variant: 'stacked' },
			},
			{
				id: WidgetKeys.tools,
				instanceId: 'exec-tools',
				position: { col: 6, row: 2 },
				size: { w: 2, h: 1 },
			},
		],
	},
]
