// Map of English city names to Persian city names
export const cityNameMap: Record<string, string> = {
	'Tehran': 'تهران',
	'Isfahan': 'اصفهان',
	'Mashhad': 'مشهد',
	'Shiraz': 'شیراز',
	'Tabriz': 'تبریز',
	'Kerman': 'کرمان',
	'Yazd': 'یزد',
	'Ahvaz': 'اهواز',
	'Qom': 'قم',
	'Kermanshah': 'کرمانشاه',
	'Urmia': 'ارومیه',
	'Rasht': 'رشت',
	'Zahedan': 'زاهدان',
	'Hamedan': 'همدان',
	'Arak': 'اراک',
	'Ardabil': 'اردبیل',
	'Bandar Abbas': 'بندرعباس',
	'Bojnord': 'بجنورد',
	'Bushehr': 'بوشهر',
	'Gorgan': 'گرگان',
	'Ilam': 'ایلام',
	'Iranshahr': 'ایرانشهر',
	'Karaj': 'کرج',
	'Khorramabad': 'خرم‌آباد',
	'Sanandaj': 'سنندج',
	'Sari': 'ساری',
	'Semnan': 'سمنان',
	'Shahrekord': 'شهرکرد',
	'Yasuj': 'یاسوج',
	'Zanjan': 'زنجان',
	'Qazvin': 'قزوین',
	'Quchan': 'قوچان',
	'Maragheh': 'مراغه',
	'Marand': 'مرند',
	'Mahabad': 'مهاباد',
	'Miandoab': 'میاندوآب',
	'Najafabad': 'نجف‌آباد',
	'Neyshabur': 'نیشابور',
	'Varamin': 'ورامین',
	'Sabzevar': 'سبزوار',
	'Abadan': 'آبادان',
	'Dezful': 'دزفول',
	'Khorramshahr': 'خرمشهر',
	'Masjed Soleyman': 'مسجدسلیمان',
	'Behbahan': 'بهبهان',
	'Borujerd': 'بروجرد',
	'Malayer': 'ملایر',
	'Nahavand': 'نهاوند',
	'Kangavar': 'کنگاور',
	'Sonqor': 'سنقر',
	'Paveh': 'پاوه',
	'Javanrud': 'جوانرود',
	'Gilan': 'گیلان',
	'Mazandaran': 'مازندران',
	'Azerbaijan': 'آذربایجان',
	'Kurdistan': 'کردستان',
	'Fars': 'فارس',
	'Khorasan': 'خراسان',
	'Khuzestan': 'خوزستان',
	'Lorestan': 'لرستان',
	'Chaharmahal and Bakhtiari': 'چهارمحال و بختیاری',
	'Kohgiluyeh and Boyer-Ahmad': 'کهگیلویه و بویراحمد',
	'Hormozgan': 'هرمزگان',
	'Sistan and Baluchestan': 'سیستان و بلوچستان',
	'Golestan': 'گلستان',
	'North Khorasan': 'خراسان شمالی',
	'Razavi Khorasan': 'خراسان رضوی',
	'South Khorasan': 'خراسان جنوبی',
	'Markazi': 'مرکزی',
	'Alborz': 'البرز',
	'West Azerbaijan': 'آذربایجان غربی',
	'East Azerbaijan': 'آذربایجان شرقی'
}

// Helper function to convert English city name to Persian
export function getPersianCityName(englishCityName: string): string {
	return cityNameMap[englishCityName] || 'تهران'
} 