name: Publish to Firefox Add-ons

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Extension Version (e.g. 1.1.4)"
        required: false
        default: ""

jobs:
  publish-firefox:
    name: Build & Publish to Firefox Add-ons
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build & Zip for Firefox
        run: bun run zip:firefox
        env:
          FIREFOX_EXTENSION_VERSION: ${{ github.event.inputs.version }}
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}

      - name: Upload Artifacts (Download from GitHub Actions)
        uses: actions/upload-artifact@v4
        with:
          name: firefox-builds
          path: .output/*-firefox.zip
          retention-days: 1

      - name: Upload Source Code Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-sources
          path: .output/*-sources.zip
          retention-days: 1

      - name: Commit and push zip to main (Temporary)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout main
          mkdir -p releases
          cp .output/*-firefox.zip releases/
          cp .output/*-sources.zip releases/
          git add releases/
          git commit -m "chore(release): temporary firefox zip files"
          git push origin main
